apiVersion: v1
kind: Service
metadata:
  labels:
    tier: frontend
    service: emailservice
  name: emailservice
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: emailservice-web
    tier: frontend
    service: emailservice
  type: LoadBalancer
